.TH "include/fonts.h" 3 "Mon Mar 2 2020" "amgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fonts.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBfonts\fP [128][8]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "char fonts[128][8]"

.SH "Author"
.PP 
Generated automatically by Doxygen for amgame from the source code\&.
