.TH "src/keyboard.c" 3 "Mon Mar 2 2020" "amgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/keyboard.c
.SH SYNOPSIS
.br
.PP
\fC#include <game\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKEYNAME\fP(key)   [_KEY_##key] = #key,"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_key\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KEYNAME(key)   [_KEY_##key] = #key,"

.SH "Function Documentation"
.PP 
.SS "void print_key ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for amgame from the source code\&.
